import Provider from "@/components/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import Footer from "@/components/Footer";
import NavigationBar from "@/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${inter.className} block w-full h-auto min-h-full bg-white dark:bg-black`}
      >
        <main className="flex flex-col w-full h-auto">
          <Provider>
            <SessionProvider session={session}>
              <NavigationBar session={session} />
              {children}
              <Footer session={session} />
              <Toaster />
            </SessionProvider>
          </Provider>
        </main>
      </body>
    </html>
  );
}
